name: media_manager
description: "A comprehensive Flutter plugin for managing media files across Android (up to API 36), iOS (up to 18.0), and macOS (up to 15.0) platforms with enhanced performance and latest OS compatibility."
version: 0.0.4
homepage: "https://github.com/SwanFlutter/media_manager"

environment:
  sdk: ^3.7.2
  flutter: '>=3.3.0'

dependencies:
  flutter:
    sdk: flutter
  plugin_platform_interface: ^2.1.8

dev_dependencies:
  flutter_test:
    sdk: flutter
  flutter_lints: ^5.0.0


flutter:

  plugin:
    platforms:
      android:
        package: com.example.media_manager
        pluginClass: MediaManagerPlugin
      ios:
        pluginClass: MediaManagerPlugin
      macos:
        pluginClass: MediaManagerPlugin


